name: Validate Keystore Before Build

on:
  workflow_run:
    workflows: ["Your Main Workflow Name"] # 替换为您的实际主工作流名称
    types: 
      - requested
      - completed

jobs:
  validate-keystore:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Decode and Validate Keystore
        run: |
          echo "正在验证密钥库和密码..."
          
          # 创建临时目录
          mkdir -p temp_keystore
          cd temp_keystore
          
          # 解码Base64密钥库
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > keystore.jks
          
          # 验证文件类型
          echo "文件类型:"
          file keystore.jks
          
          # 验证文件大小
          echo "文件大小:"
          ls -lh keystore.jks
          
          # 尝试列出密钥库内容（使用store密码）
          echo "尝试列出密钥库内容:"
          if keytool -list -v \
            -keystore keystore.jks \
            -storepass "${{ secrets.STORE_PASSWORD }}"; then
            echo "✅ 密钥库密码验证成功"
          else
            echo "❌ 密钥库密码验证失败"
            exit 1
          fi
          
          # 尝试访问特定密钥（使用key密码）
          echo "尝试访问密钥:"
          if keytool -list -v \
            -keystore keystore.jks \
            -storepass "${{ secrets.STORE_PASSWORD }}" \
            -alias "${{ secrets.KEY_ALIAS }}"; then
            echo "✅ 密钥别名和密码验证成功"
          else
            echo "❌ 密钥别名或密码验证失败"
            exit 1
          fi
          
          # 导出证书验证
          echo "导出证书:"
          keytool -exportcert -v \
            -alias "${{ secrets.KEY_ALIAS }}" \
            -keystore keystore.jks \
            -storepass "${{ secrets.STORE_PASSWORD }}" \
            -file certificate.cer
            
          openssl x509 -in certificate.cer -inform der -text -noout
          
          echo "所有验证通过！密钥库和密码有效。"
